sources:
  - Martian Mono.glyphs
axisOrder:
  - wght
  - wdth
familyName: Martian Mono
buildStatic: false
stat:
  MartianMono[wdth,wght].ttf:
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 75
    - name: SemiCondensed
      value: 87.5
    - name: Normal
      value: 100
      flags: 2
    - name: SemiExpanded
      value: 112.5
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800